# Generated by Django 3.2.12 on 2023-04-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
