# Generated by Django 4.1.7 on 2023-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='post_announce',
            field=models.TextField(),
        ),
    ]
