# Generated by Django 3.2.12 on 2023-04-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
